### ISSUE TITLE
be2-scala TODO list

### ISSUE THREAD

**Issue by RaulinN** [dedis/student_21_pop#310]
Take a look at #275 and #305  for further information

- [x] Implement the possibility to subscribe/unsubscribe from a particular channel (e.g. using actors to represent users and channel => [example](https://github.com/calvinlfer/websockets-pubsub-akka/tree/master/src/main/scala/com/experiments/calvin)) – expected ???
- [x] Implement the "Answerer" for a non-broadcast query (e.g. answer positively/negatively to the query emitter). Should be quite easy (can use the same idea as archive-be2). The implementation of the previous bullet point might change how this one should be handled – expected ???
- [x] Implement a mechanism to broadcast answers to every client subbed to a particular channel. Will be easy (using akka's MergeHub or custom merge hub implementation) once bullet point 1 will be implemented – expected ???

---

- [ ] JsonSchema validator module (doesn't exist in scala, should use the java version) – expected 2h
- [x] Update codebase with the new roll call protocol changes (#287) – expected 1-2h

---

- [x] Hook up dbActorNew to the whole DSL graph (not hard, simply need to find "the best way" to do it) – expected 1h. ℹ️  resolving this will make the whole project compile again
- [x] Correct parser according to @pierluca's review – expected 30' (_update: probably finished_)

---

- [x] Propagate (e.g. `WitnessHandler`)

---

Finishing touches : 

- [ ] Optimize imports

**Comment by pierluca** [comment]
The first and last points seem rather easily within our non-Scala-expert reach and not on the critical path. 

@RaulinN I'd suggest you leave them to us.

On the other hand, if you can look at point (2) next that would allow us to compile and verify that we're not doing too many wrong things :) 

Why do you expect the answerer to be dependent on the roll call implementation?

**Comment by RaulinN** [comment]
Alright no problem!

Will prioritize bullet point (2) then :)

That's a wording mistake ^^' That should have read "implementation of **previous** bullet point"
